name: BouncyBalls
main: com.huskydreaming.bouncyball.BouncyBallPlugin
description: Balls with Juicy Physics and Customisation
version: '${project.version}'
api-version: 1.19
author: HuskyDreaming
website: https://www.spigotmc.org/members/huskydreaming.1413607/

commands:
  bouncyballs:
    description: The bouncy-ball command.
    aliases: [bb, bball, bouncyb, bouncyball]